
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    url: jdbc:mysql://avnadmin:AVNS_-0rZilVzs1pa5MoEdbt@mysql-316b18d7-sreekanthv1995-44b1.d.aivencloud.com:26741/maxi_g_db?ssl-mode=REQUIRED
    password: AVNS_-0rZilVzs1pa5MoEdbt
  application:
    name: MAXI-G
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: https://www.googleapis.com
          client-id: "527124445285-2fo34e8jg723jaaemr4b0bnnq3jdoq8b.apps.googleusercontent.com"
          client_secret: "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"

  cloudinary:
    cloud_name: "dyb6t2awf"
    api_key: "514813724911381"
    api_secret: "a5RLuzKrUST7Ts-kIIxwMMBM0Dk"


  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: sreekanthv1995@gmail.com
    password: swysorteaomozkar
    port: '587'

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'

