
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/maxi_g_db
    password: sreekanth1995
  application:
    name: MAXI-G
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: https://www.googleapis.com
          client-id: "527124445285-2fo34e8jg723jaaemr4b0bnnq3jdoq8b.apps.googleusercontent.com"
          client_secret: "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"

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: sreekanthv1995@gmail.com
    password: swysorteaomozkar
    port: '587'

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'

